# ----------------------- #
#      Main Configs       #
# ----------------------- #
exclude: Rakefile
url: http://hamxiaoz.github.com

pygments: true
rdiscount:
  extensions: [smart]
  
# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /
#permalink: /:year/:month/:title
permalink: /blog/:year/:month/:day/:title
#source: source
#destination: public
#plugins: plugins
#code_dir: downloads/code
category_dir: blog/categories
markdown: rdiscount
#pygments: false # default python pygments have been replaced by pygments.rb

paginate: 9          # Posts per page on the blog index
pagination_dir: blog  # Directory base for pagination URLs eg. /blog/page/2/
recent_posts: 5       # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

titlecase: true       # Converts page and post titles to titlecase


# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Twitter
twitter_tweet_button: true

# Disqus Comments
disqus_short_name: hamxiaozgithubcom
disqus_show_comment_count: false

# Facebook Like
facebook_like: true
