# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: zurassic
email: your-email@domain.com
description: Andrew Zheng's personal website
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# twitter_username: jekyllrb
# github_username:  jekyll

# Markdown settings: http://kramdown.gettalong.org/parser/gfm.html
markdown: kramdown
kramdown:
  input: GFM

# Build settings
# theme: minima
permalink: /blog/:categories/:title.html
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - TODO.md


# http://jekyllrb.com/docs/configuration/
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
      logo_link: "/"
      logo_image: "/assets/images/zhi.png"
  -
    scope:
      type: "posts" # The different types that are available to you are pages, posts, drafts or any collection in your site.
    values:
      close_to_link: "/blog"